baseURL: "https://shyam.github.io"
languageCode: "en-us"
title: "Shyam"
theme: master

Paginate.pagerSize: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    darkmode:
        secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

    # darkmode:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Shyam D R"
    #subtitle: 
    content: "An SDE at Nielsen with 4+ years of experience working at Tredence and Unacademy, specializing in designing data-intensive applications, scalable systems, cloud technologies (AWS, Azure), and Devops."
    image: "images/me3.jpeg"
    # button:
    #   background - color: 
    #   enable: true
    #   name: "Resume"
    #   url: "https://drive.google.com/file/d/1JQZes_6KwxXs7ZVk_wDyil-sAW8BzQKI/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/shyamdr
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/shyamdr/
  # About
  about:
    enable: true
    title: "About me:"
    image: "/images/me1.jpeg"
    content: |
      I am a Data-Focused Software Engineer with over 4 years of experience building scalable data pipelines, designing robust software systems, and developing machine learning models. 
      
      Primarily as a Data Engineer, I am skilled at creating efficient ETL workflows, optimizing big data processes, and managing cloud-based data infrastructure using tools like Apache Spark, Airflow, Databricks, Snowflake and AWS.
      
      In my current role as SDE at Nielsen, specializing in Advertisment Intelligence, I helps clients such Amazon Prime, Netflix and YouTube to provide valuable insights on the social market trends to help them ...

      Passionate about solving complex engineering challenges, I thrive in designing and optimizing distributed systems that drive impactful solutions.  
     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Java, C++, Python, SQL, Linux"
        - "Git, Jenkins, Devops, Docker, Kubernetes, Kafka, Elasticsearch"
        - "AWS, Azure, Databricks, Snowflake, Dbt, Talend"
        - "Apache Spark, HDFS, Flink, Maven, Iceberg"
        - "Deep Learning, LLMs, Numpy, Pandas, MATLAB, NLP"
        # - ""

  # Experience
  experience:
    enable: true
    items:

      - job: "Software Engineer"
        client: "Amazon"
        company: "Nielsen"
        companyUrl: "https://www.amazon.com/"
        # date: "May 2024 - Aug 2024"
        info:
          enable: true
          content: "Location: Bangalore, KA, IND"
        featuredLink:
          enable: false
        content: |
          Bangalore, KA, IND
          - Designed end-to-end pipelines to integrate Connected TV (CTV) ads portfolio improving data accessibility and enabling a 10% increased reporting coverage.
          - Optimized storage efficiency by leveraging open-source file formats and strategic data partitioning in S3, reducing API list calls by 25% and cutting storage costs.
          - Contributed to a product matching algorithm for ads and creatives using fuzzy matching and Jaccard similarity, improving matching efficiency by 40%.
          - Contributed on cloud architecture redesign by implementing Spot EMR clusters with On-Demand instances, reducing monthly cloud costs by 25%.


      - job: "Data Engineer - 2"
        company: "Metyis"
        companyUrl: "https://www.metyis.com/"
        date: "July 2022 - Dec 2024"
        info:
          enable: true
          content: "Location: Bangalore, KA, India"
        featuredLink:
          enable: false
        content: |
          Bangalore, KA, India
          - Contributed to the architectural design of a unified analytics solution on Fabric and OneLake, integrating 10+ data sources and improving query performance by 40%
          - Collaborated on a metadata-driven ingestion framework for automated data ingestion across multiple sources, reducing data orchestration costs by 30%.

      
      - job: "Data Engineer"
        company: "Tredence"
        companyUrl: "https://www.tredence.com/"
        date: "June 2021 - June 2022"
        info:
          enable: true
          content: "Location: Bangalore, KA, India"
        featuredLink:
          enable: true
          url: "https://www.tredence.com/"
        content: |
          Bangalore, KA, India
          - Developed a robust batch ETL process to extract 10+ TB of data from Graph REST API using Azure Data Factory, Databricks and load data to Snowflake, improving data transformation efficiency
          - Improved data accessibility and query speeds by 15% by loading data into Snowflake and implementing effective Data modelling techniques.

      - job: "Intern"
        company: "Unacademy"
        companyUrl: "http://unacademy.com/"
        date: "March 2019 - August 2019"
        info:
          enable: true
          content: "Location: Mangalore, India"
        featuredLink:
          enable: true
          url: "http://unacademy.com/"
        info:
          content: 
        content: |-
          Mangalore, India
          - Designed STEM courses for students preparing for undergrad competitive exams in Physics.
          - Ensured a high satisfaction rate of 95%, with more than 20k impressions monthly.

  # Education
  education:
    enable: true
    index: true
    items:
#      - title: "Bachelor of Science in Mechanical Engineering"
#        school:
#          name: "National Institute of Technology Karnataka"
#          url: "https://engineering.nyu.edu/"
#        date: "09/2023 - 12/2024"
#        GPA: "3.83 out of 4.0"
#        content: |-
#            - Course Work:
#              - Cloud Computing
#              - Big data
#              - Information,security and Privacy
#              - Design and Analysis of algorithms
#              - Operating Systems
#              - Principles of Databases

      - title: "Bachelor of Technology in Mechanical Engineering"
        school:
          name: "National Institute of Technology Karanataka, Surathkal"
          url: "https://www.nitk.ac.in/"
        date: "2017 - 2021"
        # GPA: "8.1 out of 10"
        content: |- 
          - Published a research work in International Journal of Fluid Mechanics Research, 2021
          
          Extracurricular Activities
            - Active Volunteer, Citizens of the Great Barrier Reef by Goodera.
            - Finalist, E-Yantra robotics competition (National) hosted by IIT Bombay, 2018.
            - Executive member of NITK's robotics team participating in Robocon (International), annual robotics competition 2018-21
            - Chief Technical Lead(2021), Astro-Comittee Convener(2020), Project Coordinator(2019) of Amateur Astronomy Club, NITK

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:

    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      # - title: Women Entrepreneurship Week Candidate 2020
      #   content: Was selected to meet a Senior Director from Jio Industries for a discussion about the Smart Yoga Instructor application AIC Incubation Center at IIIT Kottayam.
      # - title: Elected Cultural Secretary 2019 - 2021
      #   content: Conducted 15+ events with a footprint of more than 300+ students and Managed a team of 25 students for fundraising and event organization # Conducted events virtually during COVID for effective engagement among new students.
      #   url: "https://www.iiitkottayam.ac.in/#!/culturalClub"
      - title: Presented my paper at the 3rd International Conference on Machine Intelligence and Signal Processing 2021. 
        content: Author of “Performance evaluation of deep learning models for word sense disambiguation” at the 3rd International Conference on Machine Intelligence and Signal Processing 2021. This paper was based on my Bachelor's Major Project and is published by Springer.
        url: https://link.springer.com/chapter/10.1007/978-981-19-0840-8_18696969
        # featured:
        #   name: Click here to know more!
        #   link: https://link.springer.com/chapter/10.1007/978-981-19-0840-8_18
      - title: Achieved a global ranking of 1131 in Codechef's Data Structures and Algorithms contest 
        content: Participated in a global competitive contest of data structures and algorithms and achieved a rank of 1131 global ranking.
      - title: HackWithInfy DataStructures and Algorithms Finalist
        content: I was a Finalist, HackWithInfy Data structures and Algorithms coding competition hosted by Infosys.
      
 # projects
  projects:
    enable: true
    items:
      - title: Most Viewed Time Frame Recommendation for YouTube Data
        content: Built a system to recommend the most engaging time frames for YouTube videos using Kafka for real-time data ingestion, MongoDB for storing video metadata, and PySpark for big data processing and analyzing user engagement trends across
          different time segments.

          Processed 50,000 requests daily with low latency, serving insights from 100,000+ interactions.

        image: /images/projects/Colorization5.png
        badges:
          - "Kafka"
          - "MongoDB"
          - "PySpark"
        
      - title: Intelligent Photo Album with Natural Language Search
        content: Developed a web application for intelligent photo album management with natural language search capabilities. Utilized AWS services such as ElasticSearch for indexing, Lambda for serverless functions, S3 for photo 
        image: /images/projects/doge4.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/shyamdr/SearchPhotos-AI
        badges:
          - "AWS"
          - "Rekognition"
          - "S3"
          - "EC2"
        links:
          - icon: fab fa-github
            url: https://github.com/shyamdr/SearchPhotos-AI

      # - title: Marketing Insights - Statistics
      #   content: Digging through data and finding significant insights to advertise better products to customers of different backgrounds.
      #   image: /images/projects/advert1.jpeg
      #   featured:
      #     name: Click here to know more!
      #     link: https://github.com/Keerthi-Sreenivas/statistics/blob/main/Project.pdf
      #   # badges:
      #   #   - "Hugo"
      #   #   - "Bootstrap"
      #   #   - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/Keerthi-Sreenivas/statistics/blob/main/Project.pdf

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: https://www.linkedin.com/in/shyamdr/
    btnName: Message me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/shyamdr
      linkedin: https://www.linkedin.com/in/shyamdr/
    # twitter: https://twitter.com
    # facebook: https://facebook.com
